### PR TITLE
Upgraded to egui 0.18.0 and Tetra 0.7.0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by tesselode** [comment]
Thank you for the PR, and sorry for the delay in getting back to you.

Would there be any major challenges in upgrading to egui 0.18.0 (which came out today)? I'm not asking you to do it specifically, but if it would be a lot of work then it might be worth publishing a new version with egui 0.17.0 support while somebody else (not me) works on 0.18.0 support.

(I say not me because to be honest, I might just archive this project, given that Tetra is no longer actively developed.)

**Comment by ghost** [comment]
No prob, I'll have a look at 0.18.
Yeah, Tetra no longer being maintained has made me wonder whether I should move my game to something else.

**Comment by ghost** [comment]
Ok, I've added egui 0.18 support. 
Just a note, the PaintCallback feature has not been implemented, so there isn't support for custom rendering inside of an egui region. https://docs.rs/epaint/0.18.0/epaint/struct.PaintCallback.html

**Comment by tesselode** [comment]
@devmeat My apologies, I totally forgot to merge this in. Do you still want me to merge it?

**Pull request closed without merging**
